version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: sage_x3_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: sage_x3_db
      MYSQL_USER: sage_x3_user
      MYSQL_PASSWORD: sage_x3_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "sage_x3_user", "-psage_x3_password"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  sage_x3_app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
      - ./final:/app/final
      - ./archive:/app/archive
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=sage_x3_user
      - MYSQL_PASSWORD=sage_x3_password
      - MYSQL_DATABASE=sage_x3_db
      - DATABASE_URL=mysql+pymysql://sage_x3_user:sage_x3_password@mysql:3306/sage_x3_db?charset=utf8mb4
      - SESSION_EXPIRY_HOURS=24
      - CLEANUP_INTERVAL_MINUTES=60
      - MAX_FILE_SIZE=16777216
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery_worker:
    build: .
    command: celery -A app.celery worker --loglevel=info --concurrency=4
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
      - ./final:/app/final
      - ./archive:/app/archive
      - ./logs:/app/logs
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=sage_x3_user
      - MYSQL_PASSWORD=sage_x3_password
      - MYSQL_DATABASE=sage_x3_db
      - DATABASE_URL=mysql+pymysql://sage_x3_user:sage_x3_password@mysql:3306/sage_x3_db?charset=utf8mb4
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_beat:
    build: .
    command: celery -A app.celery beat --loglevel=info
    volumes:
      - ./logs:/app/logs
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=sage_x3_user
      - MYSQL_PASSWORD=sage_x3_password
      - MYSQL_DATABASE=sage_x3_db
      - DATABASE_URL=mysql+pymysql://sage_x3_user:sage_x3_password@mysql:3306/sage_x3_db?charset=utf8mb4
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  flower:
    build: .
    command: celery -A app.celery flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  redis_data:
  mysql_data:
